//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoitureDB.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public string Color { get; set; }
        public int Mileage { get; set; }
        public int EnginePower { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public int DoorCount { get; set; }
        public int SeatCount { get; set; }
        public string RentalRange { get; set; }
        public double RentalBasePricePerDay { get; set; }
    }
}
