//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garage.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Identifier { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string DriverFirstName { get; set; }
        public string DriverLastName { get; set; }
        public string DriverLicenceNumber { get; set; }
        public int IdentifierVehicle { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
