--CREATE TABLE [dbo].[Customer] 
--(
--    [Identifier]          INT            IDENTITY (1, 1) NOT NULL,
--    [FirstName]           NVARCHAR (100) NOT NULL,
--    [LastName]            NVARCHAR (100) NOT NULL,
--    [DriverLicenceNumber] NVARCHAR (20)  NOT NULL,
--    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Identifier] ASC)
--);